# Generated by Django 4.2.7 on 2023-11-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesitescraper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='addres',
            new_name='address',
        ),
    ]
